name: Project test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  check:
    name: Test
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: cache-npm-${{ hashFiles('./package-lock.json') }}
          restore-keys: cache-npm-

      - name: Install dependencies
        run: npm ci

      - name: Run checks
        run: npm t
